# Enable italics
set -g default-terminal "tmux"

# Enable mouse
set -g mouse on

# Enable true color
set-option -sa terminal-overrides ",xterm*:RGB"

# Bind prefix as Ctrl-A
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

# Bind HJKL like Vim.
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Open new windows in the same directory as the current one.
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
