#!/bin/bash

die() {
  echo "$1"
  exit 1
}

lowercase() {
  echo "$1" | tr '[:upper:]' '[:lower:]'
}

DRIVE=$(lowercase "$1")
DRIVE_PATH="/mnt/$DRIVE"

if [[ $EUID -ne 0 ]]; then
  die "$0: sudo/root required" 
fi

if [[ -z "${DRIVE// }" ]]; then
  die "$0: drive letter is missing"
fi

mkdir $DRIVE_PATH

if ! mount -t drvfs $DRIVE: $DRIVE_PATH -o metadata; then
  rm -r $DRIVE_PATH
  die "$0: failed to mount $DRIVE"
fi
