#!/bin/bash

DRIVE=$1
DRIVE_PATH="/mnt/$DRIVE"

die() {
  echo "$1"
  exit 1
}

if [[ $EUID -ne 0 ]]; then
  die "$0: sudo/root required" 
fi

if [[ -z "${DRIVE// }" ]]; then
  die "$0: drive letter is missing"
fi

mkdir $DRIVE_PATH

if ! mount -t drvfs $DRIVE: $DRIVE_PATH; then
  rm -r $DRIVE_PATH
  die "$0: failed to mount $DRIVE"
fi
