theme = "dark_plus"

[editor]
line-number = "relative"
scroll-lines = 1
mouse = false
true-color = true
undercurl = true
insert-final-newline = false
shell = [
  "pwsh.exe",
  "-NoLogo",
  "-NoProfile",
  "-NoProfileLoadTime",
  "-Command",
  "$PSStyle.OutputRendering='PlainText';",
]
bufferline = "multiple"
popup-border = "all"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = true

[editor.smart-tab]
enable = false

[keys.normal]
# Discard selection when appending.
a = ["append_mode", "collapse_selection"]

# Select line above.
X = "extend_line_above"

# Navigate buffers.
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"

# Git commands.
[keys.normal.G]
# Diff
d = [":hsplit-new", ":lang diff", ":insert-output git diff"]

[keys.select]
# Discard selection and return back to normal mode.
";" = ["collapse_selection", "normal_mode"]
