theme = "maple_night"

[editor]
line-number = "relative"
mouse = false
true-color = true
undercurl = true
insert-final-newline = false
shell = ["pwsh.exe","-NoLogo","-NoProfile","-NoProfileLoadTime","-Command","$PSStyle.OutputRendering='PlainText';"]
bufferline = "multiple"
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.soft-wrap]
#enable = true

[editor.lsp]
display-messages = true
