theme = "maple"

[editor]
line-number = "relative"
scroll-lines = 1
mouse = false
true-color = true
undercurl = true
insert-final-newline = false
shell = ["pwsh.exe","-NoLogo","-NoProfile","-NoProfileLoadTime","-Command","$PSStyle.OutputRendering='PlainText';"]
bufferline = "multiple"
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true

[keys.normal]
# No arrow keys for you.
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"

# Discard selection when appending.
a = ["append_mode", "collapse_selection"]

# Select line above.
X = "extend_line_above"

# Navigate buffers.
H = ":buffer-previous"
L = ":buffer-next"

# Git commands.
[keys.normal.G]
# Diff
d = [":hsplit-new", ":lang diff", ":insert-output git diff"]

[keys.select]
# Discard selection and return back to normal mode.
";" = ["collapse_selection", "normal_mode"]
