theme = "monokai_pro"

[editor]
line-number = "relative"
mouse = false
true-color = true
undercurl = true
insert-final-newline = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
