[lanugage-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.godot]
command = "ncat"
args = ["localhost", "6005"]

[language-server.mdpls]
command = "mdpls"

[language-server.mdpls.config]
markdown.preview.auto = true

[language-server.omnisharp]
command = "omnisharp"
args = ["--languageserver"]

[language-server.csharp-ls]
command = "csharp-ls"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
cargo.features = "all"
cargo.buildScripts.enable = true
check.command = "clippy"
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
imports.granularity.group = "module"

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20
snippets_first = true
snippets_inline_by_word_tail = false
feature_words = false
feature_snippets = true
feature_unicode_input = true
feature_paths = false

[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"

[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff-lsp"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "1.", ">", "- [ ]"]
language-servers = ["marksman"]

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }
language-servers = []

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "c-sharp"
language-servers = ["scls", "csharp-ls"]
auto-format = true

[[language]]
name = "json"
auto-format = true
