[lanugage-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.godot]
command = "ncat"
args = ["localhost", "6005"]

[language-server.mdpls]
command = "mdpls"

[language-server.mdpls.config]
markdown.preview.auto = true

[language-server.csharp-ls]
command = "csharp-ls"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
cargo.features = "all"
cargo.buildScripts.enable = true
check.command = "clippy"
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
imports.granularity.group = "module"

[language-server.hx-lsp]
command = "hx-lsp"

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "1.", ">", "- [ ]"]
language-servers = ["marksman"]

[[language]]
name = "rust"
auto-format = true
#formatter = { command = "rustfmt", args = ["+nightly"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }
language-servers = []

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = ["vtsls"]
auto-format = true

[[language]]
name = "c-sharp"
comment-token = ["//", "///"]
language-servers = ["hx-lsp", "csharp-ls"]
auto-format = true

[[language]]
name = "json"
auto-format = true
